### ISSUE TITLE
Feature Request - Configure Default Thumbnail Location

### ISSUE THREAD

**Issue by mckernanin** [EveOPlus/eve-o-preview#7]
I would like to be able to configure where thumbnails spawn by default. Currently they end up in the top left of my primary monitor. A coordinate value (just like what is saved for named clients) would suffice. I have tried setting "EVE" without a character name to a coordinate value, but the clients at login screen still show in the top left of my primary monitor.

**Comment by MattCopenhaver** [comment]
Would love to see this feature.

**Comment by mckernanin** [comment]
This got added a while ago, closing it

**Comment by MattCopenhaver** [comment]
@mckernanin Can you link to instructions on how to do it?  I searched and asked and was told it’s not possible.
